name: ci

on:
  push:
    branches: [main, staging]
  pull_request:

permissions: {}

jobs:
  test:
    uses: hvpaiva/back/.github/workflows/go.yaml@main
    permissions:
      contents: read

  delivery:
    needs: test
    uses: hvpaiva/back/.github/workflows/delivery.yaml@main
    with:
      service: hello
    permissions:
      contents: write
      packages: write
